export default [
  "ROSSO","BLU","VERDE","GIALLO","VIOLA","ARANCIONE","MARRONE","NERO","BIANCO","GRIGIO",
  "ROSA","CELESTE","AZZURRO","TURCHESE","INDACO","BEIGE","AVORIO","CREMA","ORO","ARGENTO",
  "BRONZO","PORPORA","MAGENTA","FUCSIA","LILLA","LAVANDA","MALVA","SALMONE","CORALLO","TERRACOTTA",
  "OCRA","SENAPE","CANARINO","LIMONE","OLIVA","SMERALDO","GIADA","ACQUAMARINA","CIANO","CARMINIO",
  "BORDEAUX","AMARANTO","CIOCCOLATO","CAFFE","CASTANO","NOCCIOLA","SABBIA","PANNA","PERLA","ANTRACITE",
  "PIOMBO","ARDESIA","GRANATA","CREMISI","VERMIGLIO","ZAFFERANO","CURCUMA","PISTACCHIO","MENTA","GHIACCIO",
  "CIELO","NOTTE","PETROLIO","COBALTO","ELETTRICO","NEON","PASTELLO"
];
