export default [
  "TESTA","FACCIA","FRONTE","OCCHIO","OCCHI","NASO","BOCCA","LABBRO","LABBRA","LINGUA",
  "DENTE","DENTI","MENTO","GUANCIA","GUANCE","ORECCHIO","ORECCHIE","COLLO","GOLA","SPALLA",
  "SPALLE","BRACCIO","BRACCIA","GOMITO","GOMITI","POLSO","POLSI","MANO","MANI","DITO",
  "DITA","POLLICE","INDICE","MEDIO","ANULARE","MIGNOLO","UNGHIA","UNGHIE","PETTO","TORACE",
  "SCHIENA","PANCIA","ADDOME","OMBELICO","FIANCO","FIANCHI","ANCA","ANCHE","GAMBA","GAMBE",
  "COSCIA","COSCE","GINOCCHIO","GINOCCHIA","POLPACCIO","CAVIGLIA","PIEDE","PIEDI","TALLONE","PIANTA",
  "ALLUCE","CAPELLI","CAPELLO","CIGLIA","PALPEBRA","IRIDE","PUPILLA","CERVELLO","CUORE","POLMONE",
  "POLMONI","FEGATO","RENE","RENI","STOMACO","INTESTINO","MUSCOLO","MUSCOLI","OSSO","OSSA",
  "SCHELETRO","SANGUE","VENA","VENE","ARTERIA","NERVO","NERVI","PELLE","TENDINE","COLONNA",
  "VERTEBRA","MASCELLA","BARBA","BAFFI","RUGA","RUGHE","VOCE","RESPIRO","SUDORE"
];
