export default [
  "MELA","PERA","BANANA","ARANCIA","LIMONE","FRAGOLA","CILIEGIA","PESCA","ALBICOCCA","SUSINA",
  "PRUGNA","UVA","KIWI","ANANAS","MANGO","PAPAYA","COCCO","MELONE","ANGURIA","POMPELMO",
  "MANDARINO","CLEMENTINA","LAMPONE","MIRTILLO","MORA","RIBES","MELAGRANA","FICO","DATTERO","NOCE",
  "NOCCIOLA","MANDORLA","PISTACCHIO","CASTAGNA","POMODORO","PATATA","CAROTA","ZUCCHINA","MELANZANA","PEPERONE",
  "CIPOLLA","AGLIO","SEDANO","FINOCCHIO","CAVOLO","BROCCOLO","SPINACIO","LATTUGA","INSALATA","RUCOLA",
  "RAVANELLO","RAPA","BARBABIETOLA","ZUCCA","CETRIOLO","FAGIOLINO","PISELLO","FAVA","LENTICCHIA","CECE",
  "ASPARAGO","CARCIOFO","FUNGO","TARTUFO","CACHI","NESPOLA","CORBEZZOLO","GIUGGIOLA","CARAMBOLA","LITCHI",
  "GUAVA","MARACUJA","STELLINA","RABARBARO","CAPPERO","CAPPUCCINA","INDIVIA","RADICCHIO","SCAROLA","VALERIANA",
  "BIETOLA","COSTA","ERBETTA","PORRO","SCALOGNO","PREZZEMOLO","BASILICO","ORIGANO","ROSMARINO","SALVIA",
  "TIMO","MENTA","ALLORO","MAGGIORANA","ANETO","TOPINAMBUR","SEDANORAPA","CAVOLFIORE","VERZA","CAVOLINO",
  "CARDO","COCOMERO","CANTALUPO","PAPRIKA","PEPERONCINO","ZENZERO","CURCUMA"
];
