export default [
  "ITALIA","FRANCIA","SPAGNA","GERMANIA","PORTOGALLO","GRECIA","SVIZZERA","AUSTRIA","BELGIO","OLANDA",
  "IRLANDA","DANIMARCA","SVEZIA","NORVEGIA","FINLANDIA","POLONIA","UNGHERIA","ROMANIA","BULGARIA","CROAZIA",
  "SERBIA","SLOVENIA","SLOVACCHIA","UCRAINA","RUSSIA","TURCHIA","ISLANDA","MALTA","CIPRO","LUSSEMBURGO",
  "STATIUNITI","CANADA","MESSICO","BRASILE","ARGENTINA","CILE","PERU","COLOMBIA","VENEZUELA","URUGUAY",
  "PARAGUAY","BOLIVIA","ECUADOR","CUBA","GIAMAICA","CINA","GIAPPONE","COREA","INDIA","PAKISTAN",
  "INDONESIA","VIETNAM","TAILANDIA","MALESIA","FILIPPINE","MONGOLIA","NEPAL","BHUTAN","MYANMAR","CAMBOGIA",
  "LAOS","EGITTO","MAROCCO","ALGERIA","TUNISIA","LIBIA","NIGERIA","KENYA","ETIOPIA","GHANA",
  "SENEGAL","ANGOLA","MOZAMBICO","ZAMBIA","ZIMBABWE","NAMIBIA","BOTSWANA","AUSTRALIA","NUOVAZELANDA","FIGI",
  "SAMOA","TONGA","ISRAELE","GIORDANIA","LIBANO","SIRIA","IRAQ","IRAN","AFGHANISTAN","KAZAKISTAN",
  "UZBEKISTAN","GEORGIA","ARMENIA","AZERBAIGIAN"
];
