export default [
  "MEDICO","AVVOCATO","INGEGNERE","INSEGNANTE","INFERMIERE","FARMACISTA","DENTISTA","ARCHITETTO","MECCANICO","ELETTRICISTA",
  "IDRAULICO","MURATORE","FALEGNAME","SARTO","PARRUCCHIERE","BARBIERE","CUOCO","PANETTIERE","MACELLAIO","PESCATORE",
  "AGRICOLTORE","PASTORE","VETERINARIO","PSICOLOGO","GIORNALISTA","SCRITTORE","PITTORE","SCULTORE","MUSICISTA","CANTANTE",
  "ATTORE","REGISTA","FOTOGRAFO","GRAFICO","INFORMATICO","CONTABILE","BANCARIO","COMMESSO","CASSIERE","MAGAZZINIERE",
  "AUTISTA","PILOTA","MARINAIO","SOLDATO","POLIZIOTTO","CARABINIERE","POMPIERE","GUARDIA","PORTIERE","CAMERIERE",
  "BARISTA","SOMMELIER","GIARDINIERE","BIOLOGO","CHIMICO","FISICO","MATEMATICO","ASTRONOMO","GEOLOGO","ARCHEOLOGO",
  "STORICO","FILOSOFO","TRADUTTORE","INTERPRETE","NOTAIO","GIUDICE","SENATORE","DEPUTATO","SINDACO","DIPLOMATICO",
  "AMBASCIATORE","OSTETRICA","CHIRURGO","ANESTESISTA","RADIOLOGO","CARDIOLOGO","PEDIATRA","OCULISTA","OTORINO","DERMATOLOGO",
  "GINECOLOGO","UROLOGO","LOGOPEDISTA","ALLENATORE","ARBITRO","CALCIATORE","NUOTATORE","CICLISTA","MARATONETA","ISTRUTTORE",
  "ANIMATORE","HOSTESS","STEWARD","CONTROLLORE","MACCHINISTA","FERROVIERE","VIGILE","TASSISTA","CORRIERE","FATTORINO",
  "IMBIANCATORE","GEOMETRA","TOPOGRAFO","URBANISTA","RESTAURATORE","ORAFO","GIOIELLIERE","OROLOGIAIO","TAPPEZZIERE","CERAMISTA",
  "VETRAIO","FABBRO","TORNITORE","SALDATORE","CARPENTIERE","GRUISTA","MINATORE","APICOLTORE","VITICOLTORE","CASARO",
  "PANIFICATORE","PASTICCIERE","GELATAIO","SCENOGRAFO","COSTUMISTA","DOPPIATORE","CANTASTORIE","BURATTINAIO","ILLUSIONISTA","ACROBATA",
  "GIOCOLIERE","DOMATORE"
];
