export default [
  "CALCIO","TENNIS","NUOTO","CICLISMO","ATLETICA","PALLAVOLO","BASKET","PALLANUOTO","RUGBY","GOLF",
  "SCHERMA","JUDO","KARATE","TAEKWONDO","BOXE","PUGILATO","GINNASTICA","SCI","SNOWBOARD","SLITTINO",
  "PATTINAGGIO","HOCKEY","BADMINTON","SQUASH","CANOTTAGGIO","CANOA","VELA","SURF","TUFFI","TRIATHLON",
  "MARATONA","CORSA","SALTO","LANCIO","EQUITAZIONE","TIRO","ARCIERIA","MOTOCICLISMO","ARRAMPICATA","ALPINISMO",
  "MOTOCROSS","BILIARDO","BOWLING","CRICKET","BASEBALL","SOFTBALL","FRISBEE","SKATEBOARD","PARKOUR","YOGA",
  "PILATES","CROSSFIT","SOLLEVAMENTO","CURLING","BOB","SLALOM","DISCESA","FONDO","BIATHLON","TRAMPOLINO",
  "PALLAMANO","FUTSAL","BEACHVOLLEY","TENNISTAVOLO","PADEL","BOCCE","PETANQUE","FRECCETTE","SCACCHI","DAMA",
  "BRIDGE","POKER","REMO","KAYAK","RAFTING","KITESURF","WINDSURF","PARAPENDIO","DELTAPLANO","SPELEOLOGIA",
  "ORIENTEERING","DUATHLON","PENTATHLON","DECATHLON","EPTATHLON","MEZZOFONDO","VELOCITA","OSTACOLI","ASTA","GIAVELLOTTO",
  "DISCO","MARTELLO","PESO","STAFFETTA","MARCIA","TRIPLO"
];
